#!/bin/sh
set -e
if type systemctl >/dev/null 2>/dev/null; then
	OPTS=""

	if [ -n "$D" ]; then
		OPTS="--root=$D"
	fi

	if [ "enable" = "enable" ]; then
		for service in nfs-statd.service; do
			case "${service}" in
			*@*)
				systemctl ${OPTS} enable "${service}"
				;;
			esac
		done
	fi

	if [ -z "$D" ]; then
		systemctl daemon-reload
		systemctl preset nfs-statd.service

		if [ "enable" = "enable" ]; then
			systemctl --no-block restart nfs-statd.service
		fi
	fi
fi
